### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Link-Zhang** [CodeDaraW/Hacker#1]
Hi, I like your theme. But when I used, the index's blog does not show a brief in the list, while they are listed all. What do I missed? Could you help me ?

**Comment by Link-Zhang** [comment]
你好，我很喜欢你的主题。但是我在使用的时候，主页的文章不会以缩略的形式呈现，而是全部列出，导致主页非常长。请问，我怎么设置才能像你的主页一样精简呢？多谢！

**Comment by CodeDaraW** [comment]
Use a html comment with the word "more" to mark the excerpt of your post, like this:
```
title: post title
---
This part is the excerpt, get it with the <%- post.excerpt %>
<!-- more --> 
```
All the text after the` <!-- more -->` is only displayed when you view the page of the post.  
Reference: https://github.com/hexojs/hexo/issues/1143  

使用单词“more”在html中添加注释来标记出文章的摘要部分，例如这样：  
```
title: post title
---
This part is the excerpt, get it with the <%- post.excerpt %>
<!-- more --> 
```
` <!-- more -->` 后面的文字只有在查看文章时才会显示出来。  
参考： https://github.com/hexojs/hexo/issues/1143

**Comment by CodeDaraW** [comment]
@Link-Zhang

**Comment by Link-Zhang** [comment]
Thank  you for your great help.
非常感谢！
