### ISSUE TITLE
您好下载之后：hexo server FATAL end of the stream or a document separator is expected at line 6, column 1:     title: Hexo

### ISSUE THREAD

**Issue by GeekHades** [CodeDaraW/Hacker#13]
<img width="651" alt="screen shot 2017-01-07 at 15 04 26" src="https://cloud.githubusercontent.com/assets/12511107/21740141/9958a49e-d4ea-11e6-8bf4-2a2465706cb5.png">

部署的出现了这个问题：
➜  blog hexo server
FATAL end of the stream or a document separator is expected at line 6, column 1:
    title: Hexo

**Comment by CodeDaraW** [comment]
目测这个不是主题的问题，是Hexo的YAML解析组件的问题。  
可以试试看使用默认主题有没有这样的问题。
