### ISSUE TITLE
[问题] 请问如何修改网页的favicon？

### ISSUE THREAD

**Issue by dxGuan** [CodeDaraW/Hacker#15]
rt：
   请问如何修改网页的favicon？

**Comment by CodeDaraW** [comment]
`layout/components/head.ejs`中引用favicon的代码：
``` ejs
<link href="<%- config.root %>favicon.ico" rel="icon">
```
所以在Hexo博客文件夹中找到`source`文件夹，将`favicon.ico`文件放进去即可。  

当然你也可以自己修改favicon的引用位置，但是上面的是推荐的做法。

**Comment by dxGuan** [comment]
请问是将favicon.ico 放到 Hacker下的source/images文件夹吗？
如果是的话，我目前就是这样做的
当hexo generate后，确实在public/images下找到favicon.ico
但hexo server后，貌似没有作用（即没有显示icon）

**Comment by CodeDaraW** [comment]
不是，举个我的例子，当前目录是整个博客的目录：

```  bash
➜  hexo git:(master) ✗ tree -L 2
.
├── _config.yml
├── db.json
├── package.json
├── public
│   ├── 2015
│   ├── 2016
│   ├── 2017
│   ├── about
│   ├── archives
│   ├── atom.xml
│   ├── categories
│   ├── CNAME
│   ├── css
│   ├── favicon.ico
│   ├── images
│   ├── img
│   ├── index.html
│   ├── links
│   ├── page
│   ├── sitemap.xml
│   └── tags
├── scaffolds
│   ├── draft.md
│   ├── page.md
│   └── post.md
├── source
│   ├── about
│   ├── CNAME
│   ├── favicon.ico
│   ├── img
│   ├── links
│   └── _posts
└── themes
    ├── hacker
    └── hackerold

310 directories, 13 files
```

其中Hacker主题应该在`themes`文件夹中，而`favicon.ico`文件应该放在`source`文件夹中。

**Comment by CodeDaraW** [comment]
`Hacker`下的`source/images`文件夹是主题的图片资源文件夹。

**Comment by dxGuan** [comment]
恩，我已经按你的结构进行了修改（将favicon.ico放回到source目录下）
但hexo generate后还是不行

**Comment by CodeDaraW** [comment]
执行`hexo s`后浏览器清除缓存强制刷新试试看

**Comment by CodeDaraW** [comment]
`hexo g`后查看下`public`文件夹中有没有`favicon.ico`文件以及是否正确，`public`文件夹下是最终生成的整个站点的所有文件，如果正确的话那就是缓存了。

**Comment by dxGuan** [comment]
恩，好的，谢谢
