### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by mohitgarg** [CodeDaraW/Hacker#18]
How can I add an about page about the author of the blog. I added the links in the menu `menu:
  Home: /
  Archives: /archives
  About: /about` like this but it won't generate anything. I get an error saying Cannot GET /about/. And Whenever I generate for deployment it shows files generated but the files are not working correctly. Here's the link for the
[repo](https://github.com/mohitgarg/mohitgarg.github.io/tree/master/public)

**Comment by CodeDaraW** [comment]
You should create a folder named `about` in the folder `source`, then add a file named `index.md`  like this: 
```
➜  hexo git:(master) ✗ tree -L 3 -I 'node_modules'
.
├── _config.yml
├── db.json
├── package.json
├── public
...
├── scaffolds
│   ├── draft.md
│   ├── page.md
│   └── post.md
├── source
│   ├── _posts
│   │   ├── es6-static-class.md
...
│   │   └── vue-watcher.md
│   ├── about
│   │   └── index.md
│   ├── categories
│   │   └── index.md
│   ├── CNAME
│   ├── favicon.ico
│   ├── img
│   ├── links
│   │   └── index.md
│   └── tags
│       └── index.md
└── themes
 ...
  
```

and edit `index.md` like this: 
```
title: About
date: 2015-07-30
---
## About Me
Something about me.
```

BTW, it's a question about Hexo, so perhaps you should read the docs of Hexo for more info.

**Comment by mohitgarg** [comment]
I am sorry yes I found the answer in the docs but the second one is about the theme. Did you take a look at the repo? It's the folder generated by hexo but the theme is not working

**Comment by CodeDaraW** [comment]
Obviously, you put the generator site in a subdirectory, but you don't config correctly in the global configure file `_config.yml`:
``` yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 
root: 
```
So it seems to be a question about Hexo too.

**Comment by mohitgarg** [comment]
![capture](https://cloud.githubusercontent.com/assets/14136405/24322417/150f7c1c-118a-11e7-80e5-aaf25aa4b739.PNG)
Can you please tell me what am I doing wrong? It would be a great help and save me a lot of time

**Comment by CodeDaraW** [comment]
You may try it that set the `url` as `https://mohitgarg.github.io/public` and set the `root` as `/public/`.

**Comment by mohitgarg** [comment]
Thankyou so much. 💯
