### ISSUE TITLE
修改字体和格式

### ISSUE THREAD

**Issue by CooSamuel** [CodeDaraW/Hacker#22]
想问一下如何调整markdown的格式和字体。hacker主题怎么使用cdn的Google字体之类？在[Daraw](https://blog.daraw.cn/2015/08/25/build-blog-with-github-pages-for-free/)只有的light的介绍

**Comment by CodeDaraW** [comment]
这就需要你自己修改源码了，里面是硬编码实现的，开发之初也并没有考虑这个需求。  
字体相关的代码在`/source/css/components/layout.styl`中。
