### ISSUE TITLE
你好，我用了你的主题后，发现有时候网页会卡死，上下滚动不了，麻烦能帮忙看看吗

### ISSUE THREAD

**Issue by andmizi** [CodeDaraW/Hacker#24]

**Comment by CodeDaraW** [comment]
请报告你的浏览器版本，确定是否是你的浏览器版本的问题。
这个主题里并没有JS（第三方统计、评论等等除外），除非页面非常大导致内存占用过大，否则是不会导致卡死的问题的。

**Comment by andmizi** [comment]
Microsoft Edge 40.15063.0.0
360浏览器也出现过一次，出现的几率不大，会不会引用了第三方评论插件导致的

**Comment by CodeDaraW** [comment]
edge不是很容易卡死吗(大雾

说正经事，第三方JS只有Disqus和Google Analysis，他们用户那么多应该不至于会有严重的问题，所以我还是怀疑是浏览器本身的问题。

建议你试试在主题配置项中取消评论和Google分析的使用，看看还会不会出现卡顿。

最好的话还是请你帮忙看看能不能稳定或者大概率复现某个页面的卡顿？

**Comment by andmizi** [comment]
我改了搜狐的畅言  下次碰到了 我尝试复现下 谢谢你了

**Comment by CodeDaraW** [comment]
好的，不客气~
