### ISSUE TITLE
首页展示文章的全部内容

### ISSUE THREAD

**Issue by sunzq19931016** [CodeDaraW/Hacker#26]
您好，我在用您的模版之后首页显示文章的全部内容，能显示一部分么？

**Comment by CodeDaraW** [comment]
Why not search for it before asking?  
#1

**Comment by sunzq19931016** [comment]
没有明白什么意思

**Comment by CodeDaraW** [comment]
Issues里已经有几个类似的提问，问之前为什么不搜索一下呢？在 #1  里我已经回答的很详细了。  
另外Google也可以得到答案：https://www.google.com/search?q=hexo+首页+显示缩略

抱歉之前态度不是很好，只是遇到了几次这种现象后，容易失去耐心。

**Comment by sunzq19931016** [comment]
谢谢，也是我没有表达清楚，我想问的是 除了 还有其他的解决方法么？
现在我已经明白了，谢谢！！！ O(∩_∩)O~~

**Comment by CodeDaraW** [comment]
客气~  
可能这是在不去hack框架的前提下的唯一的解决方法了。  
虽然我没读过源码，大概的猜测hexo应该是通过类似注释实现了标注，在解析的时候会记录下来。如果有其他方法大概也逃脱不掉这种思路。

**Comment by sunzq19931016** [comment]
之前我是用多说进行评论 现在多说关闭了。
我现在使用的是[来必力](https://livere.co)的评论，并且替换了comment.ejs下的代码，你可以试试。

**Comment by CodeDaraW** [comment]
Thanks~
暂时没有更换的想法，继续用Disqus也挺好的。
