### ISSUE TITLE
主页摘要问题

### ISSUE THREAD

**Issue by CyrusF** [CodeDaraW/Hacker#28]
可否在 config 中增加一个摘要的固定长度，实现固定长度摘要

**Comment by CodeDaraW** [comment]
这样是可以实现的，但是未来并不打算加入这个feature。

实现原理很简单，参考[变量 | Hexo](https://hexo.io/zh-cn/docs/variables.html)，直接`slice`文章的`content`。

__那么为什么不这样做呢？__
因为固定的长度`slice`会导致中文出现奇怪的断词、英文单词被截断等等排版的问题；相比之下，在文章的MD源文件里加一行注释代价并不大，不但摘要长度可控而且会有更好的排版效果。
