### ISSUE TITLE
gitment 评论初始化

### ISSUE THREAD

**Issue by MuBeiSAMA** [CodeDaraW/Hacker#40]
我这边在new gitment 的时候不填id评论没办法初始化，看了老哥的代码发现也没填但是能正常评论，想了解一下是怎么解决的。

**Comment by CodeDaraW** [comment]
我都填写了的

**Comment by MuBeiSAMA** [comment]
![image](https://user-images.githubusercontent.com/30261823/52840792-545e3a80-3135-11e9-9977-6b72f443e321.png)
这个位置的id

**Comment by CodeDaraW** [comment]
这是我最终页面的代码，参考 view-source:https://blog.daraw.cn/2018/09/07/video-quality-monitor/
``` html
<script>
    var gitment = new Gitment({
        owner: 'CodeDaraW',
        repo: 'Blog',
        oauth: {
            client_id: '9f8c0418f979e3f9436d',
            client_secret: '3cb6eb7ebba52973d5d4083533b8eba117462319',
        },
    })
    gitment.render('gitment')
</script>
```

**Comment by CodeDaraW** [comment]
https://github.com/imsun/gitment，构造 `Gitment` 实例对象的时候，`id` 参数是选填的，按道理应该没有问题，你确定下最终生成的页面代码有没问题。

**Comment by MuBeiSAMA** [comment]
找到原因了，gitment的id会以label的形式打在评论对应的issues上，label有50字符的长度限制，我的location.href过长了，所以初始化失败，只要把id对应的值改成个短一点的就解决了。感谢 @CodeDaraW 回复

**Comment by CodeDaraW** [comment]
不客气，这个是属于 Gitment 的问题了，解决了就好。
