### ISSUE TITLE
加了<!-- more -->后，没有显示readmore字样或者阅读全文之类的提示？

### ISSUE THREAD

**Issue by scoful** [CodeDaraW/Hacker#45]
RT

**Comment by CodeDaraW** [comment]
只是没显示提示，列表页已经是只展示 `<!-- more -->` 前面的内容了。

**Comment by scoful** [comment]
怎么弄才能首页只显示标题

**Comment by CodeDaraW** [comment]
没试过，`<!-- more -->` 加在文章最前面应该可行。

**Comment by CodeDaraW** [comment]
BTW，这是 hexo 的问题，可以去 hexo issues 提问。

**Comment by yipengh** [comment]
@scoful @CodeDaraW 
不知是否已解决了问题。
在`_config.yml`中加入以下配置可显示`阅读全文`：
```yaml
theme_config:
  read_more_btn: true
```
