### ISSUE TITLE
文章增加TOC功能

### ISSUE THREAD

**Issue by whiteCcinn** [CodeDaraW/Hacker#47]
希望文章可以加一个TOC的功能

**Comment by CodeDaraW** [comment]
暂时不考虑，该主题的定位是为了简化排版，TOC 某种程度上增加了排版的复杂度。

**Comment by whiteCcinn** [comment]
@CodeDaraW 确实是，挑了好久，还是你这个看着比较舒服。

**Comment by CodeDaraW** [comment]
如果有兴趣的话，可以 fork 一份，基于 fork 开发 TOC 功能，效果不错的话可以提 PR，再作 review。
