### ISSUE TITLE
大佬，能不能支持下mathjax公式和自动目录生成？

### ISSUE THREAD

**Issue by cyd1st** [CodeDaraW/Hacker#49]

**Comment by CodeDaraW** [comment]
1. MathJax 公式这个我是不打算支持的，参考 #30 ，你可以看下他的 Fork 能否满足你的需求，如果不行可以 Fork 他的仓库后修改 MathJax 配置。

2. 自动目录生成我不太理解你说的是什么样的，我的理解是 archives，这个 Hexo 默认自带的，参考 https://blog.daraw.cn/archives/ 。

**Comment by cyd1st** [comment]
感谢回复。目录是指markdown中的toc，也就是文章的目录。hexo插件库中我只找到手动的，自动是指根据标题 #，生成目录。

**Comment by CodeDaraW** [comment]
明白了，这个的话我这边是不打算再去动这个主题的排版了，不过你可以放到文章主体部分的开头。 
我这边有个思路是：配成自动化构建，加一个 git hook，在 commit 的时候自动给 md 文件构建头部的目录索引。
