### ISSUE TITLE
使用Github Action自动发布后, 首页menu缺失

### ISSUE THREAD

**Issue by liunaijie** [CodeDaraW/Hacker#57]
我在使用Github Action自动发布后, 发现首页上的[首页, 归档, 关于]这些菜单会消失, 但是在本地发布是可以的, 所以想请教下这个是什么原因

**Comment by CodeDaraW** [comment]
有更详细的信息吗，可以看下构建后最终的配置文件对不对

**Comment by CodeDaraW** [comment]
因为项目不希望自带一个配置文件，避免用户的放进来后冲突，所以只提供了一个 example 配置文件。  
实际在 CI 环境中应该自行创建主题配置文件，然后链接到主题的文件夹下，例如这个是我的博客的 Netlify 构建配置，GitHub Actions 也是一样的思路，可以参考下：
![image](https://user-images.githubusercontent.com/12277082/163367865-f6f2b541-b114-4ef3-8fbe-8ea89aece48f.png)

**Comment by liunaijie** [comment]
我也清楚你这样做的目的, 找到原因后解决的方法就有很多了.   
能否在readme上给用户添加一个这样的提示, 从而避免后续的issue

**Comment by CodeDaraW** [comment]
明白，现在都不怎么维护这个了，有余力的话欢迎提个 PR 哈哈
