### ISSUE TITLE
页面详情后我想时间到秒该如何修改

### ISSUE THREAD

**Issue by joywqy** [CodeDaraW/Hacker#63]
现在的时间都是2023-03-10 ，我想2023-03-10 09:09:09 该如何实现，谢谢

**Comment by CodeDaraW** [comment]
页面对应位置的源代码在这里
https://github.com/CodeDaraW/Hacker/blob/9c5801ed32cbf074a3f4bacd80a1bd193d12e2d8/layout/components/article.ejs#L21

参考文档 [配置 - 日期 / 时间格式](https://hexo.io/zh-cn/docs/configuration#%E6%97%A5%E6%9C%9F-x2F-%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F)，修改配置文件中的 `date_format` 即可。
