### ISSUE TITLE
请问如何更改博客名字的字体？

### ISSUE THREAD

**Issue by masterrite** [CodeDaraW/Hacker#64]
我在header.styl里改了font-family以后没什么变化：
> site-branding
    text-align center
    margin-bottom 2rem
    font-family "Apple Chancery", italic
    letter-spacing 0.1em
    text-transform

谢谢！

**Comment by masterrite** [comment]
发布了以后貌似在电脑端改好了，但是在手机端还是没有更改，而且手机端的图标也是原来的。请问手机端怎么改？谢谢！

**Comment by CodeDaraW** [comment]
可以先看下是不是缓存的问题，另外看你申明的字体是某个系统独有的，你确认下是否手机端系统有对应的字体。  
另外一个保险的做法是用 `font-face` 自己定义和加载下字体文件。

**Comment by masterrite** [comment]
> 可以先看下是不是缓存的问题，另外看你申明的字体是某个系统独有的，你确认下是否手机端系统有对应的字体。 另外一个保险的做法是用 `font-face` 自己定义和加载下字体文件。

谢谢！我自己下载了字体放在source文件夹里，然后在css文件里都改好了。
