### ISSUE TITLE
title

### ISSUE THREAD

**Issue by youbingtiantian** [CodeDaraW/Hacker#68]
在关于情况下favicon旁是显示的About，但是在归档情况下 favicon旁显示的就是归档，我希望都是显示单词，这是bug还是什么。

**Comment by CodeDaraW** [comment]
这里的 About 实际上没做特殊处理，About 是作为一个普通 post 出现的，所以如果你的博客和我的一样，「关于」原文档中的标题就是「About」的话，那浏览器的标题里就是「About」，如果手动改成中文的「关于」应该就可以符合你的要求了。  
你可以试一下看看。

**Comment by youbingtiantian** [comment]
> 这里的 About 实际上没做特殊处理，About 是作为一个普通 post 出现的，所以如果你的博客和我的一样，「关于」原文档中的标题就是「About」的话，那浏览器的标题里就是「About」，如果手动改成中文的「关于」应该就可以符合你的要求了。 你可以试一下看看。

我其实希望他是英文，我希望归档也是英文，不过问题不大拉，我的博客和你的一样的，我是使用你的！很漂亮简洁

**Comment by CodeDaraW** [comment]
奥，如果是希望是英文的话，你把语言切成 en-US 就好了，这样全局的文案都是英文。主题的代码里适配了 en-US 和 zh-CN 的文案。  
参考：https://hexo.io/zh-cn/docs/internationalization

**Comment by youbingtiantian** [comment]
> 奥，如果是希望是英文的话，你把语言切成 en-US 就好了，这样全局的文案都是英文。主题的代码里适配了 en-US 和 zh-CN 的文案。 参考：https://hexo.io/zh-cn/docs/internationalization

好的，谢谢拉
