### ISSUE TITLE
图片加载

### ISSUE THREAD

**Issue by youbingtiantian** [CodeDaraW/Hacker#69]
你好，请问你的图片是如何加载的那么快的，如何处理呀

**Comment by CodeDaraW** [comment]
看图片的地址，我放在大陆的 CDN 上了。  
用 GitHub Pages 会比较慢，你可以试试用 Netlify 部署或者套个 Cloudflare CDN 试试，这些都是免费的，可能会快些。  
如果条件允许的话，可以用国内云服务厂商的 CDN。

**Comment by youbingtiantian** [comment]
> 看图片的地址，我放在大陆的 CDN 上了。 用 GitHub Pages 会比较慢，你可以试试用 Netlify 部署或者套个 Cloudflare CDN 试试，这些都是免费的，可能会快些。 如果条件允许的话，可以用国内云服务厂商的 CDN。

好的好的，原本的github pages实在是太慢了，我也用cdn吧，谢谢。
