### ISSUE TITLE
建议：添加Tag功能

### ISSUE THREAD

**Issue by aimer1124** [CodeDaraW/Hacker#7]

**Comment by CodeDaraW** [comment]
建议收到～  

也曾经考虑过要不要加Tag和Category的问题，感觉加了后会导致导航那块变得更大，而一般情况文章的条数并没有多到需要Tag和Category的程度。  

目前这个功能也不确定加不加，如果加的话可能会放在主题的配置文件中让选择是否开启。

这个Issue先开着，等有结论了再来关闭。

**Comment by Thea-R** [comment]
同建议！
折腾了半天tag页面，现在才发现原来没添加这功能😭

**Comment by icanfly** [comment]
同建议加上。tag功能还是有很大用处的。

**Comment by CodeDaraW** [comment]
下个版本添加～

**Comment by zzq2015** [comment]
加吧，另外期待可以出新版本

**Comment by CodeDaraW** [comment]
各位抱歉拖了这么久，已经更新了([Add support for categories and tags](https://github.com/CodeDaraW/Hacker/commit/2ab311c080ffebf20bfc30c3a748f91b5e268642))，具体的使用方法请参考Readme文档，感谢各位的建议，让大家久等了。

**Comment by Thea-R** [comment]
不好意思，我想问一下更新是不是不能显示标签云？

**Comment by CodeDaraW** [comment]
并不是实现成了标签云的样子，具体的使用方法参考Readme。
