### ISSUE TITLE
可以加分享功能嘛？

### ISSUE THREAD

**Issue by Mr-Binary** [CodeDaraW/Hacker#8]
漂亮的主题，WP时代就一直用，多谢制作

插话：可以加分享功能嘛？分享到Facebook，twitter，G+这种

**Comment by CodeDaraW** [comment]
不用谢～

抱歉并不打算添加分享功能，分享工具众多，难免众口难调。
如果需要这个功能建议你可以fork一份后在自己喜好的位置添加喜好的分享插件提供的代码。

**Comment by Mr-Binary** [comment]
Thanks, 暂时也只能这样了🤓我学习下，有不懂的再来问🤓thanks
