### ISSUE TITLE
Deploy Hacker themed Hexo blog to Github not working

### ISSUE THREAD

**Issue by lony** [CodeDaraW/Hacker#9]
Currently, the Hacker theme seems to not be supported by Github. Building it with the `hexo deploy --generate` command results in the following error:

```
The page build failed with the following error:

The hacker theme is not currently supported on GitHub Pages. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

How can I deploy the blog with your theme using the following [source](https://github.com/lony/lony.github.io)?

**Comment by CodeDaraW** [comment]
I just tried using your [source](https://github.com/lony/lony.github.io), however it functions well.   
I guess there might be something wrong with your enviroment, but not the theme.
You'd better check the enviroment of your system.

PS: `username.github.io` is a special repository, and you might not need `gh-pages` branch.

**Comment by lony** [comment]
You were right, I deployed the page to another repository it showed something (even the style and css was not available - no relative linking).

Then I used the `username.github.io` repo and deployed directly to master and it works!

Maybe it is a good idea to add a FAQ part to your repo?

Thanks for your help!

**Comment by CodeDaraW** [comment]
You are welcome~
